---
  version: "3"
  services: 
    node: 
      image: "becodeorg/node"
      environment: 
        NODE_ENV: "development"
      volumes: 
        - "./package.json:/src/app/package.json"
        - "./node_modules:/src/app/node_modules"
        - "./bin:/src/app/bin"
      expose: 
        - "12345"
        - "9229"
      ports: 
        - "80:12345"
        - "9229"
      command: "nodemon --inspect=0.0.0.0:9229 --watch bin"
    mongo: 
      image: "mongo"
      restart: "unless-stopped"
      ports: 
        - "27017:27017"
      volumes: 
        - "mongo_db:/data/db"
      environment: 
        MONGO_INITDB_ROOT_USERNAME: "dev"
        MONGO_INITDB_ROOT_PASSWORD: "dev"
  volumes: 
    mongo_db: 
